### PR TITLE
v3.0.4

### LINKED ISSUE #257: Bridge and Farmer are sending to many SUBSCRIBE messages
### Package Versions

Replace the values below using the output from `npm list storj`.

```
"title":"Storj Bridge",
"version":"0.9.3",
"description":"Access the Storj network using a simple REST API.",
"x-protocol-version":"0.7.1",
"x-core-version":"1.4.0"
```

Replace the values below using the output from `node --version`.

```
I don't know
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

10 bridge minnions. All have the same nodeID. Bridge is uploading shards. All shards with the same opcode. 
```
skunk@Server010:~$ grep '"0f01' onehourbridgelog.log | wc -l
2371
skunk@Server010:~$ grep '"0e01' onehourbridgelog.log | wc -l
40
```

I would expect a total of 60 SUBSCRIBE messages in the first 15 minutes and later 0 SUBSCRIBE messages. 10 minnions sending 3 SUBSCRIBE each. 30 for the tunnel PUBLISH messages and 30 for one opcode.

Lets take the worst case and calculate with all 81 opcodes. In that case I would expect 2460 SUBSCRIBE messages in the first 15 minutes.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The bridge is sending more SUBSCRIBE messages than PUBLISH even after hours.

```
skunk@Server010:~$ grep 'sending PUBLISH' onehourbridgelog.log | wc -l
76462
skunk@Server010:~$ grep 'sending SUBSCRIBE' onehourbridgelog.log | wc -l
96000
```

I checked the last 3 hours to see if it is always the same number.
```
grep '2016-07-12T14' storj-bridge.Server012.log | grep 'sending SUBSCRIBE' | wc -l
102566
grep '2016-07-12T13' storj-bridge.Server012.log | grep 'sending SUBSCRIBE' | wc -l
111153
grep '2016-07-12T12' storj-bridge.Server012.log | grep 'sending SUBSCRIBE' | wc -l
100415
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start bridge server and keep it running for a few hours
2. Check the logfile. Ignore the first hour. We don't want to track the startup messages.

### LINKED ISSUE #328: Stop relay old contract PUBLISH
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
└─┬ storjshare-cli@5.0.2
  └── storj@2.2.0
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Relay only valid contract PUBLISH messages
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

contract PUBLISH messages are comming with a timeout. My node will not send any OFFER message if the contract PUBLISH message is to old but my node will still relay the old contract PUBLISH message. This will result in a high amount of contract PUBLISH spam messages. Everyone will relay them but nobody can send an OFFER.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Generate a nodeID close to a bridge server and start farming. (To receive more PUBLISH messages because of https://github.com/Storj/storjshare-cli/issues/122#issuecomment-239612014)
2. Check the number of received contract PUBLISH messages and the number of received contract messages.

### LINKED ISSUE #345: Min Reqs File
Could you have a file here on github which lists the min reqs and their versions respectively for nodejs/python/git?

Referencing:
https://github.com/Storj/storj-automation/issues/46

### LINKED ISSUE #347: File upload task stops and exits without error  (core v.3.0.3) - windows 10
### Package Versions

npm --version: 2.15.9

node --version: 4.5.0

core version : 3.0.3

OS: windows 10 home edition

### Expected Behavior

clean exit with 'failed-upload message' or continuous retry of upload.

### Actual Behavior

7bec37370199f889f3 to frame
 [Thu Aug 18 2016 23:21:48 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 0f1f87cc21d1107cd20458336d43727c07dda54e to frame
 [Thu Aug 18 2016 23:21:53 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 82d38aeeaa21b0d4dd2c5c8643f5298f879a8977 to frame
 [Thu Aug 18 2016 23:21:55 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 2b68ac9089705628cf4449a16a94d56838432cb5 to frame
 [Thu Aug 18 2016 23:21:57 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8317ac5abc3fb9cdda4defbdc089fa0c62f6dea0 to frame
 [Thu Aug 18 2016 23:21:58 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 4e788d71f9ce64260d2d65b1e6123fbbd43e5f4e to frame
 [Thu Aug 18 2016 23:22:02 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8970ed8333fa8d599c702e7bec37370199f889f3 to frame
 [Thu Aug 18 2016 23:22:04 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 0f1f87cc21d1107cd20458336d43727c07dda54e to frame
 [Thu Aug 18 2016 23:22:09 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 82d38aeeaa21b0d4dd2c5c8643f5298f879a8977 to frame
 [Thu Aug 18 2016 23:22:10 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Thu Aug 18 2016 23:22:10 GMT+0200 (W. Europe Daylight Time)] [warn]   Error occured. Triggering cleanup...
 [Thu Aug 18 2016 23:22:10 GMT+0200 (W. Europe Daylight Time)] [info]   Cleaning up...
 [Thu Aug 18 2016 23:22:11 GMT+0200 (W. Europe Daylight Time)] [info]   Finished cleaning!
 [Thu Aug 18 2016 23:22:11 GMT+0200 (W. Europe Daylight Time)] [error]  No storage offers were received
 [Thu Aug 18 2016 23:22:13 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8317ac5abc3fb9cdda4defbdc089fa0c62f6dea0 to frame
 [Thu Aug 18 2016 23:22:18 GMT+0200 (W. Europe Daylight Time)] [info]   Adding shard metadata for 8970ed8333fa8d599c702e7bec37370199f889f3 to frame

C:\WINDOWS\system32>

### Steps to Reproduce

upload a file.

### PR DESCRIPTION
**Pull request by bookchin**
* Update to `kad-quasar@0.2.0`
* Prevent mulitple join callbacks
* Prevent duplicate subscriptions
* Closes #257 
* Closes https://github.com/Storj/storjshare-cli/issues/122
* Closes #328 
* Closes #345
* Closes #347

### CODE REVIEW

File: lib/network/index.js [hunk 1]
```diff
@@ -574,7 +621,7 @@ Network.prototype._setupTunnelClient = function(callback) {
       self._logger.info(
         'you are publicly reachable, skipping tunnel establishment'
       );
-      self._listenForTunnelers();
+      // self._listenForTunnelers();
```
Comment (bookchin) [inline lib/network/index.js]: Remove me

File: lib/network/index.js [hunk 2]
```diff
@@ -741,7 +788,7 @@ Network.prototype._establishTunnel = function(tunnels, callback) {
 
         tunnelWasOpened = true;
 
-        self._listenForTunnelers();
+        // self._listenForTunnelers();
```
Comment (bookchin) [inline lib/network/index.js]: Remove me
