### PR TITLE
v3.2.0

### LINKED ISSUE #377: uploading multiple files does not work
### Package Versions

```
3.1.0
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

```
should upload all files in a folder
```

### Actual Behavior

```
does not upload any files in the foldr  (should have one file in it)

C:\>storj upload-file 57c3a9f281e21cfd4f3d973f C:\folder
 [Mon Aug 29 2016 21:37:19 GMT-0400 (Eastern Daylight Time)] [info]   0 file(s)
to upload.
 [...]  > Enter your passphrase to unlock your keyring  >  **************

 [Mon Aug 29 2016 21:37:28 GMT-0400 (Eastern Daylight Time)] [info]   Generating
 encryption key...

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. C:\folder
2. Put a txt banlog.txt
3. Run the command above

### LINKED ISSUE #385: Storj CLI upload-file --recursiv including subfolders
As farmer I would like to have a --recursiv flag for `storj upload-file`. That will allow me to upload all files including subfolders. Without --recursiv flag I would like to upload only the files in that directory exclusiv subfolders.

### LINKED ISSUE #396: Invalid Array Buffer Length
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
├── storj@3.1.0
└─┬ storj-bridge-client@0.4.3
  └── storj@0.6.16
```

Replace the values below using the output from `node --version`.

```
v5.1.0
```

I'm using the wrong version number. But I think this is reproducible across versions. Will downgrade and try again.

### Expected Behavior

Upload proceeds until completion. 

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [info]   [ dump2 ] Storing file, hang tight!
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames","method":"POST","json":{"__nonce":"93b2e57b-6ea0-4293-98e7-935e36dd5864"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"304502207a7ac5ac33183764b1ed96ad2e060b022c6399b0fb0496046d50299628f82611022100ed9d3ce15431e0c4a501cd7d64d4557a8c1af10741789c9d228a09e312a96f16"}}
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"user":"cats@storj.io","shards":[],"size":0,"locked":false,"created":"2016-08-31T17:44:46.990Z","id":"57c7178e274ee8b3253b69e2"}
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\work\AppData\Local\Temp\c6a8e567c74f index 0
 [Wed Aug 31 2016 13:45:12 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: 20aa0cf37b5d71653333eb4a718f60f1d4f38262
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 20aa0cf37b5d71653333eb4a718f60f1d4f38262 (retry: 0)
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames/57c7178e274ee8b3253b69e2","method":"PUT","json":{"hash":"20aa0cf37b5d71653333eb4a718f60f1d4f38262","size":2147483648,"index":0,"challenges":["ddcfce75440de584e22f45ba52b62f04c76e8ace1378881a8a55dd44ed5a0242","8bf9f20a9a63d2fca8e5149ea56e76a11d1ebcb4207f6a770a13293596a08e5f","e207a7b5048c1dbdcaaa97a09dad130e648a6a997c67d9220cb2abcfddf62b77"],"tree":["e6983a5f9d0936650f37e23e57929bb30e84a6c4","beacf5c7e9173c7c72a397ddb5f96946858fdc38","2212628d64dd521af144932157bf5022b495d6cc","b472a266d0bd89c13706a4132ccfb16f7c3b9fcb"],"exclude":[],"__nonce":"3c770145-5f8b-4a02-98a1-6c339cdc35e2"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"304502206b4dbb60d53756a985cc256e5d362df48db78558b05ce9cf4be4d80e73f0762b022100958896121bfa61f8f13c99fc2bc14224cdb7498b870e2819982760c783831e21"}}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"hash":"20aa0cf37b5d71653333eb4a718f60f1d4f38262","token":"984b8f5cad136a1091adb4717dafd7e8d014558f","operation":"PUSH","farmer":{"protocol":"0.8.0-STAGING","address":"104.196.127.153","port":4000,"nodeID":"061bc46c36e33747e622639ecddfb8422a76746b","lastSeen":1472665541408}}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0-STAGING","address":"104.196.127.153","port":4000,"nodeID":"061bc46c36e33747e622639ecddfb8422a76746b","lastSeen":1472665541408}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
 [Wed Aug 31 2016 13:48:15 GMT-0400 (Eastern Daylight Time)] [info]   Shard transfer completed! 49 remaining...
 [Wed Aug 31 2016 13:48:16 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\work\AppData\Local\Temp\2a8bad9d2e07 index 1
 [Wed Aug 31 2016 13:49:30 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: 5378db53d7aeff8913801fb35d7f590fa395d949
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 5378db53d7aeff8913801fb35d7f590fa395d949 (retry: 0)
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames/57c7178e274ee8b3253b69e2","method":"PUT","json":{"hash":"5378db53d7aeff8913801fb35d7f590fa395d949","size":2147483648,"index":1,"challenges":["1a2e42f6136816de43c1a7b572fe4ab1cce9346d0c3b5a2ca9e6a43f0744aa50","83a4d444b9f557c2504578c61eb5443c4b31c2e7543c3351922543e57e66a05d","a49e1230d5bf43e8fcb39238b74fab1cf91e27d22d2e49ca4a715b52eeb2f5c0"],"tree":["144bda546d289c7b95dbe3fc28d1ea25c40eb290","102554b9be43252c52cb1bbc36e1597355721910","8fff483aaa1cda6f926d138d872e1240deb4eaae","b472a266d0bd89c13706a4132ccfb16f7c3b9fcb"],"exclude":[],"__nonce":"14e7f503-1fec-4384-be33-6080598768cf"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"3045022016aedbd755cca191601d39c3198a46c127e6673840f5bea17b91f507569e419c022100a4d5b7c2aaf5565b9e63e1902c5245d05a0d3d18d6e47afdf5e4c3742aaa0878"}}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"hash":"5378db53d7aeff8913801fb35d7f590fa395d949","token":"a1320812f31a4a76cc6d73c42d1588751d1ec1b7","operation":"PUSH","farmer":{"protocol":"0.8.0-STAGING","address":"104.196.117.75","port":4000,"nodeID":"6412ecb5763de95452ebf3273b4fa43f746efb74","lastSeen":1472665858389}}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0-STAGING","address":"104.196.117.75","port":4000,"nodeID":"6412ecb5763de95452ebf3273b4fa43f746efb74","lastSeen":1472665858389}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
buffer.js:98
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at allocate (buffer.js:98:17)
    at new Buffer (buffer.js:49:12)
    at allocNewPool (fs.js:1685:10)
    at ReadStream._read (fs.js:1784:5)
    at ReadStream.Readable.read (_stream_readable.js:328:10)
    at readableAddChunk (_stream_readable.js:147:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1822:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload 100 GB file for the lulz
2. Crashes after 1-2 shards

### LINKED ISSUE #401: Entering an invalid file ID to download-file gives no error
### Package Versions

```
/usr/local/lib
├── storj@3.1.1
└─┬ storjshare-cli@5.0.2
  └── storj@2.2.0
```

```
v4.4.7
```

### Expected Behavior

An error message should be displayed to the user if an invalid ID is given in download-file.
```
storj -k a download-file 57cf5bea8c71dce55bc751a5 IScWXZLTPcNrj10Yi9Lp abc.txt
[error] IScWXZLTPcNrj10Yi9Lp is not a valid file ID.  Be sure you are providing the ID, and not the file name.
```

### Actual Behavior

Program just terminates, with no indication that anything happened.

```
chris@sophia:~/storj/3.1.1Test1$ storj -k a download-file 57cf5bea8c71dce55bc751a5 IScWXZLTPcNrj10Yi9Lp abc.txt
chris@sophia:~/storj/3.1.1Test1$
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. issue download-file with an invalid file ID to download.

### LINKED ISSUE #407: core 1.3.1 upload error ('return binding.rmdir(pathModule._makeLong(path));' )
### Package Versions

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
   └── storj --version: 3.1.1

```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

clean exit

### Command
```

storj -k meije0612 -c 20 upload-file 57af3a1e8f266a7d4e391055 D:\20GB

```

### Actual Behavior

```

 [Thu Sep 08 2016 07:47:40 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 08 2016 07:47:57 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for d8b78d7852c01b7e8fdf8084169ac8c8c31f1430 (retry: 7)
 [Thu Sep 08 2016 07:48:45 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for d8b78d7852c01b7e8fdf8084169ac8c8c31f1430 (retry: 8)
 [Thu Sep 08 2016 07:48:46 GMT+0200 (W. Europe Daylight Time)] [info]   Trying to upload shard D:\temp\4859ae922333 index 19
 [Thu Sep 08 2016 07:48:46 GMT+0200 (W. Europe Daylight Time)] [info]   Hash for this shard is: 17a3eea26d83c17e54721e8679b90d897ffd4248
 [Thu Sep 08 2016 07:48:47 GMT+0200 (W. Europe Daylight Time)] [info]   Audit generation for shard done.
 [Thu Sep 08 2016 07:48:47 GMT+0200 (W. Europe Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Thu Sep 08 2016 07:48:47 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for ea7589c6052b303335ba22f1ce98eddfd6d48f3a (retry: 0)
 [Thu Sep 08 2016 07:48:48 GMT+0200 (W. Europe Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.1","address":"neomark.go.ro","port":4070,"nod
eID":"26469e2a9d0fdcaabb782e89268fdecbebf08e6b","lastSeen":1473313723888}
 [Thu Sep 08 2016 07:48:49 GMT+0200 (W. Europe Daylight Time)] [info]   Data channel opened, transferring shard...
 [Thu Sep 08 2016 07:49:09 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for ea7589c6052b303335ba22f1ce98eddfd6d48f3a (retry: 1)
 [Thu Sep 08 2016 07:49:21 GMT+0200 (W. Europe Daylight Time)] [warn]   Failed to upload shard...
 [Thu Sep 08 2016 07:49:21 GMT+0200 (W. Europe Daylight Time)] [warn]   [ 20GB ] Error occurred. Triggering cleanup...
 [Thu Sep 08 2016 07:49:21 GMT+0200 (W. Europe Daylight Time)] [info]   [ 20GB ] Cleaning up...
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir 'D:\temp\storj-4108p7ID3YI6mCJw'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at _rmdirRecursiveSync (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:285:10)
    at _cleanupCallback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\tmp\lib\tmp.js:409:5)
    at cleanup (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\bin\actions\files.js:163:15)
    at UploadState.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\bin\actions\files.js:204:27)
    at _handleError (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:494:18)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:528:16
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:346:16
    at Request._callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\lib\bridge-client\index.js:982:14)
    at Request.self.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)

C:\Windows\system32>

```

### Steps to Reproduce

upload a large file

### LINKED ISSUE #408: files finding for upload error (\node_modules\glob\sync.js:329)
### Package Versions

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
    └── storj --version@1.3.1

```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

clean exit

### Actual Behavior

```
C:\Windows\system32>storj -k meije0612 upload-file 57af3a1e8f266a7d4e391055 C:\Windows/**/*
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:329
        throw er
        ^

Error: EPERM: operation not permitted, scandir 'C:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at GlobSync._readdir (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:276:41)
    at GlobSync._readdirInGlobStar (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:255:20)
    at GlobSync._readdir (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:264:17)
    at GlobSync._processReaddir (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:136:22)
    at GlobSync._process (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:131:10)
    at GlobSync._processGlobStar (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:368:10)
    at GlobSync._process (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:129:10)
    at GlobSync._processGlobStar (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:371:10)
    at GlobSync._process (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:129:10)
    at GlobSync._processGlobStar (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:371:10)
    at GlobSync._process (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:129:10)
    at GlobSync._processGlobStar (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:371:10)
    at GlobSync._process (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:129:10)
    at GlobSync._processGlobStar (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\globule\node_modules\glob\sync.js:371:10)

C:\Windows\system32>
```

### Steps to Reproduce

upload the windows directory.

### LINKED ISSUE #411: Check Available RAM Before Setting Shard Size
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
├── storj@3.1.0
└─┬ storj-bridge-client@0.4.3
  └── storj@0.6.16
```

Replace the values below using the output from `node --version`.

```
v4.4.5
```

### Expected Behavior

Upload proceeds until completion. 

### Actual Behavior

Shard size exceeded available memory.

```
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [info]   [ dump2 ] Storing file, hang tight!
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames","method":"POST","json":{"__nonce":"93b2e57b-6ea0-4293-98e7-935e36dd5864"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"304502207a7ac5ac33183764b1ed96ad2e060b022c6399b0fb0496046d50299628f82611022100ed9d3ce15431e0c4a501cd7d64d4557a8c1af10741789c9d228a09e312a96f16"}}
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"user":"cats@storj.io","shards":[],"size":0,"locked":false,"created":"2016-08-31T17:44:46.990Z","id":"57c7178e274ee8b3253b69e2"}
 [Wed Aug 31 2016 13:44:57 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\work\AppData\Local\Temp\c6a8e567c74f index 0
 [Wed Aug 31 2016 13:45:12 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: 20aa0cf37b5d71653333eb4a718f60f1d4f38262
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 20aa0cf37b5d71653333eb4a718f60f1d4f38262 (retry: 0)
 [Wed Aug 31 2016 13:45:51 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames/57c7178e274ee8b3253b69e2","method":"PUT","json":{"hash":"20aa0cf37b5d71653333eb4a718f60f1d4f38262","size":2147483648,"index":0,"challenges":["ddcfce75440de584e22f45ba52b62f04c76e8ace1378881a8a55dd44ed5a0242","8bf9f20a9a63d2fca8e5149ea56e76a11d1ebcb4207f6a770a13293596a08e5f","e207a7b5048c1dbdcaaa97a09dad130e648a6a997c67d9220cb2abcfddf62b77"],"tree":["e6983a5f9d0936650f37e23e57929bb30e84a6c4","beacf5c7e9173c7c72a397ddb5f96946858fdc38","2212628d64dd521af144932157bf5022b495d6cc","b472a266d0bd89c13706a4132ccfb16f7c3b9fcb"],"exclude":[],"__nonce":"3c770145-5f8b-4a02-98a1-6c339cdc35e2"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"304502206b4dbb60d53756a985cc256e5d362df48db78558b05ce9cf4be4d80e73f0762b022100958896121bfa61f8f13c99fc2bc14224cdb7498b870e2819982760c783831e21"}}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"hash":"20aa0cf37b5d71653333eb4a718f60f1d4f38262","token":"984b8f5cad136a1091adb4717dafd7e8d014558f","operation":"PUSH","farmer":{"protocol":"0.8.0-STAGING","address":"104.196.127.153","port":4000,"nodeID":"061bc46c36e33747e622639ecddfb8422a76746b","lastSeen":1472665541408}}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0-STAGING","address":"104.196.127.153","port":4000,"nodeID":"061bc46c36e33747e622639ecddfb8422a76746b","lastSeen":1472665541408}
 [Wed Aug 31 2016 13:45:52 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
 [Wed Aug 31 2016 13:48:15 GMT-0400 (Eastern Daylight Time)] [info]   Shard transfer completed! 49 remaining...
 [Wed Aug 31 2016 13:48:16 GMT-0400 (Eastern Daylight Time)] [info]   Trying to upload shard C:\Users\work\AppData\Local\Temp\2a8bad9d2e07 index 1
 [Wed Aug 31 2016 13:49:30 GMT-0400 (Eastern Daylight Time)] [info]   Hash for this shard is: 5378db53d7aeff8913801fb35d7f590fa395d949
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Audit generation for shard done.
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Waiting on a storage offer from the network...
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [info]   Querying bridge for contract for 5378db53d7aeff8913801fb35d7f590fa395d949 (retry: 0)
 [Wed Aug 31 2016 13:51:08 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.staging.storj.io","uri":"/frames/57c7178e274ee8b3253b69e2","method":"PUT","json":{"hash":"5378db53d7aeff8913801fb35d7f590fa395d949","size":2147483648,"index":1,"challenges":["1a2e42f6136816de43c1a7b572fe4ab1cce9346d0c3b5a2ca9e6a43f0744aa50","83a4d444b9f557c2504578c61eb5443c4b31c2e7543c3351922543e57e66a05d","a49e1230d5bf43e8fcb39238b74fab1cf91e27d22d2e49ca4a715b52eeb2f5c0"],"tree":["144bda546d289c7b95dbe3fc28d1ea25c40eb290","102554b9be43252c52cb1bbc36e1597355721910","8fff483aaa1cda6f926d138d872e1240deb4eaae","b472a266d0bd89c13706a4132ccfb16f7c3b9fcb"],"exclude":[],"__nonce":"14e7f503-1fec-4384-be33-6080598768cf"},"headers":{"x-pubkey":"03026d072b0612c7b419c16bfd811760e34551e9422a1c5a95d2516896b1fc124f","x-signature":"3045022016aedbd755cca191601d39c3198a46c127e6673840f5bea17b91f507569e419c022100a4d5b7c2aaf5565b9e63e1902c5245d05a0d3d18d6e47afdf5e4c3742aaa0878"}}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"hash":"5378db53d7aeff8913801fb35d7f590fa395d949","token":"a1320812f31a4a76cc6d73c42d1588751d1ec1b7","operation":"PUSH","farmer":{"protocol":"0.8.0-STAGING","address":"104.196.117.75","port":4000,"nodeID":"6412ecb5763de95452ebf3273b4fa43f746efb74","lastSeen":1472665858389}}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [info]   Contract negotiated with: {"protocol":"0.8.0-STAGING","address":"104.196.117.75","port":4000,"nodeID":"6412ecb5763de95452ebf3273b4fa43f746efb74","lastSeen":1472665858389}
 [Wed Aug 31 2016 13:51:09 GMT-0400 (Eastern Daylight Time)] [info]   Data channel opened, transferring shard...
buffer.js:98
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at allocate (buffer.js:98:17)
    at new Buffer (buffer.js:49:12)
    at allocNewPool (fs.js:1685:10)
    at ReadStream._read (fs.js:1784:5)
    at ReadStream.Readable.read (_stream_readable.js:328:10)
    at readableAddChunk (_stream_readable.js:147:16)
    at ReadStream.Readable.push (_stream_readable.js:110:10)
    at onread (fs.js:1822:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload 100 GB file for the lulz
2. Crashes after 1-2 shards

### LINKED ISSUE #416: Implement a local blacklist for bad farmers on Storj CLI side

### LINKED ISSUE #418: Consider pulling the CLI into it's own module

### LINKED ISSUE #424: Working directory option
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj 3.1.2
```

Replace the values below using the output from `node --version`.

```
v4.4.7
```

### Expected Behavior

Option or environment variable needs to be available to set the working directory for uploading files.

```

```

### Actual Behavior

File encryption and other workfiles are stored in /tmp on Linux based system.  This is often small, fast, storage and is inappropriate when sending large files.  For example, 4-8GB of tmpfs space (ramdisk if you will) is commonly allocated on Linux systems for /tmp.  This suffices for virtually all regular system activity but is totally unsuitable when sending large, say 10+GB, storj files.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### LINKED ISSUE #425: Local bad farmer blacklist doesn't expire
Code review result of https://github.com/Storj/core/issues/416 / https://github.com/Storj/core/pull/403

While the renter is uploading shards he will add farmer to his local blacklist. As far as I can see the blacklist never expire. A short disconnect, crash because of a new issue, CPU or network spike and farmer get blacklisted for a very long time. I see 2 possible problems:

1.) The storj.dk bridge is uploading non stop. Sooner or later the bridge will add everyone to the blacklist and not receive any non blacklisted OFFER. At that point the bridge will start spamming the network to death.
2.) In Order to get more shards myself I can start spamming other nodes. More and more renter will add them to there blacklist.

Easy solution:
Blacklist nodeID should expire after X Minutes / Hours

Better soultion:
Blacklist nodeID should expire after 10 Minutes but don't delete the Information. Just flag it as expired. 
Next failed upload -> Backlist the nodeID again but this time for 30 minutes and than 1 hour, 10 hours, 1 day, 1 week, 1 month, what ever. Remove the nodeID or reset the expired offset after one sucessfull upload.

### PR DESCRIPTION
**Pull request by aleitner**
* Closes #401
* Closes #377
* Closes #385
* Closes #407
* Closes #411
* Closes #396
* Closes #416
* Closes #408
* Closes #418
* Closes #424
* Closes #425

https://github.com/Storj/core-cli

### CODE REVIEW

File: bin/storj.js [hunk 1]
```diff
@@ -36,6 +36,8 @@ program._storj.loglevel = function() {
 };
 
 program._storj.PrivateClient = function(options) {
+  options.blacklistFolder = DATADIR;
```
Comment (bookchin) [inline bin/storj.js]: Instead of supplying a folder to write a file into, what do you think about just supplying a file path?

File: bin/actions/files.js [hunk 2]
```diff
@@ -326,8 +339,13 @@ module.exports.download = function(bucket, id, filepath, env) {
   }
 
   module.exports.getInfo.call(self, bucket, id, function(file) {
+
```
Comment (bookchin) [inline bin/actions/files.js]: Kill this line break

File: bin/utils.js [hunk 3]
```diff
@@ -45,8 +45,13 @@ module.exports.getNewPassword = function(msg, callback) {
 };
 
 module.exports.makeTempDir = function(callback) {
+  var dir = process.env.STORJ_TEMP;
```
Comment (bookchin) [inline bin/utils.js]: Add line break here

File: lib/bridge-client/blacklist.js [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+ */
+function Blacklist(folder) {
+  if (!(this instanceof Blacklist)) {
+    return new Blacklist(folder);
+  }
+
+  assert.ok(utils.existsSync(folder), 'Invalid Blacklist Folder');
+
+  this.blacklistFile = path.join(folder,'.blacklist');
+
```
Comment (bookchin) [inline lib/bridge-client/blacklist.js]: Kill this line break

File: lib/bridge-client/index.js [hunk 5]
```diff
@@ -451,14 +459,19 @@ BridgeClient.prototype._shardUploadWorker = function(task, done) {
  * @param {UploadState} state - The upload state machine
  */
 BridgeClient.prototype._handleShardStream = function(shard, i, frame, state) {
+  var tmpdir = process.env.STORJ_TEMP;
```
Comment (bookchin) [inline lib/bridge-client/index.js]: Add line break here

File: package.json [hunk 6]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "storj",
-  "version": "3.1.2",
+  "version": "3.1.3",
```
Comment (bookchin) [inline package.json]: 3.2.0 (minor version increment - *added* functionality in a backwards compatible way)

File: lib/bridge-client/blacklist.js [hunk 7]
```diff
@@ -0,0 +1,62 @@
+'use strict';
+
+var assert = require('assert');
+var fs = require('fs');
+var utils = require('../utils');
+var path = require('path');
+
+/**
+ * Blacklist
```
Comment (bookchin) [inline lib/bridge-client/blacklist.js]: Can you add a better descriptions here for the docs
