### PR TITLE
Key ring import and export capabilities

### LINKED ISSUE #280: Add a keyring import/export method to core and cli
Add `#import(path, [password])` and `#export(path)`.

* https://github.com/alanhoff/node-tar.gz
* Also add `export-keyring` and `import-leyring` methods to storj CLI

### LINKED ISSUE #296: keyring password not consistent
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
2.0.7
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

all keys in my keyring should be encrypted with the same password

```

```

### Actual Behavior

when uploading files in the cli the keyring password should be always the same but when uploading a new file I can give an incorrect keyring password and it will be used to encrypt the new file.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. set a keyring password 
2. upload a file using a password different than the one you set

### PR DESCRIPTION
**Pull request by aleitner**
* Closes #280 
* Closes #296

### CODE REVIEW

File: bin/storj.js [hunk 1]
```diff
@@ -436,11 +436,11 @@ var ACTIONS = {
             return log('error', err.message);
           }
 
-          log('info', 'File was successfully removed from bucket.');
-          keyring.deleteKeyFromKeyRing(fileId);
-        });
+        log('info', 'File was successfully removed from bucket.');
```
Comment (bookchin) [inline bin/storj.js]: Got some weird tabs/spacing going on here.

File: lib/keyring.js [hunk 2]
```diff
@@ -66,6 +67,53 @@ KeyRing.prototype._migrateOld = function(oldPath) {
 };
 
 /**
+* @param {String} keyring - path to keyring to be compressed
+* @param {String} tar - Path to compressed keyring
+ */
+KeyRing.prototype.export = function(tar, callback) {
+  var read = targz().createReadStream(this._keyFolder);
+  var write = fs.createWriteStream(tar);
```
Comment (bookchin) [inline lib/keyring.js]: Can we check if the path already exists and if so callback with an error refusing to overwrite?

File: lib/keyring.js [hunk 3]
```diff
@@ -66,6 +67,53 @@ KeyRing.prototype._migrateOld = function(oldPath) {
...
+
+/**
+ *
+ */
+KeyRing.prototype.import = function(tar, passphrase, callback) {
+  var self = this;
+
+  function worker(entry, done) {
+    var key = path.basename(entry.path);
+    if (key === 'key.ring' || key === '.DS_Store') {
```
Comment (bookchin) [inline lib/keyring.js]: Line breaks before and after this IF block pl0x

File: lib/keyring.js [hunk 4]
```diff
@@ -66,6 +67,53 @@ KeyRing.prototype._migrateOld = function(oldPath) {
...
+      entry.resume();
+      entry.end();
+      return;
+    }
+    if (!fs.existsSync(path.join(self._keyFolder, key))) {
+      var buf = '';
+      entry.on('data', function(data) {
```
Comment (bookchin) [inline lib/keyring.js]: line break here too pl0x

File: lib/keyring.js [hunk 5]
```diff
@@ -66,6 +67,53 @@ KeyRing.prototype._migrateOld = function(oldPath) {
 };
 
 /**
+* @param {String} keyring - path to keyring to be compressed
+* @param {String} tar - Path to compressed keyring
+ */
+KeyRing.prototype.export = function(tar, callback) {
+  var read = targz().createReadStream(this._keyFolder);
+  var write = fs.createWriteStream(tar);
+  read.pipe(write).on('finish', callback).on('error', callback);
```
Comment (bookchin) [inline lib/keyring.js]: line break before this pl0x
